### ISSUE TITLE
Gridsome Develop throws error

### ISSUE THREAD

**Issue by Slgoetz** [jakedohm/gridsome-source-craftql#1]
When I run `gridsome develop` and the plugin is active I get the error of `Unexpected token < in JSON at position 4`
<img width="727" alt="Screen Shot 2019-07-22 at 9 09 12 AM" src="https://user-images.githubusercontent.com/393000/61634916-643bf680-ac60-11e9-92f0-76adc54e2306.png">

I have nothing changed from the gridsome install and this is the first time setting this all up.

**Comment by vjandrei** [comment]
I have the same but token < in JSON at position 0

**Comment by Slgoetz** [comment]
I believe it was a setup error
